name: update tide calendar

on:
  schedule:
    - cron: "0 22 * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"


    - name: Install
      run: |
        pip install -r requirements.txt


    - name: Generate ICS
      run: |
        python tide.py


    - name: Save
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "update tide" || exit 0
        git push
