name: update tide

on:
  schedule:
    - cron: "0 22 * * *"

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - run:
        pip install -r requirements.txt

    - run:
        python tide.py

    - run:
        git add .
        git commit -m "update tide"
        git push
